import type { Product } from './types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p-001',
    name: 'Wood Chair Dark Brown',
    description: 'WoodyFurniture new products...',
    category: 'Furniture',
    price: 240,
    weight: 12.5,
    sku: 'UY3749',
    rating: 4.2,
    quantity: 38,
    image: 'https://via.placeholder.com/40',
    status: 'new',
  },
  {
    id: 'p-002',
    name: 'Kitchen Table',
    description: 'Solid oak kitchen table',
    category: 'Furniture',
    price: 780,
    weight: 35,
    sku: 'UY3750',
    rating: 4.5,
    quantity: 12,
    image: 'https://via.placeholder.com/40',
    status: 'active',
  },
  {
    id: 'p-003',
    name: 'Blue Armchair',
    description: 'Comfortable blue armchair',
    category: 'Chairs',
    price: 240,
    weight: 18,
    sku: 'UY3748',
    rating: 4.1,
    quantity: 29,
    image: 'https://via.placeholder.com/40',
    status: 'deactive',
  },
  {
    id: 'p-004',
    name: 'Patio Decor Set',
    description: 'Outdoor decor set',
    category: 'Decor',
    price: 190,
    weight: 8.5,
    sku: 'UY3761',
    rating: 3.9,
    quantity: 16,
    image: 'https://via.placeholder.com/40',
    status: 'active',
  },
]